version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: adminrnp
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - rnp-network

volumes:
  grafana-storage:

networks:
  rnp-network:
    external: true
    name: rnp-network
