{
 "title": "RNP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "[ PING ] - % PERDA DE PACOTES ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  packet_loss_percent AS \"Perda de Pacotes Google\"\r\nFROM ping_metrics\r\nWHERE target = 'google.com'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  packet_loss_percent AS \"Perda de Pacotes UOL\"\r\nFROM ping_metrics\r\nWHERE target = 'uol.com.br'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  packet_loss_percent AS \"Perda de Pacotes RNP\"\r\nFROM ping_metrics\r\nWHERE target = 'rnp.br'\r\n"
    }
   ]
  },
  {
   "title": "[ HTTP ] - STATUS CODE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_status_code AS \"Status Google\"\r\nFROM ping_metrics\r\nWHERE target = 'google.com'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_status_code AS \"Status UOL\"\r\nFROM ping_metrics\r\nWHERE target = 'uol.com.br'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_status_code AS \"Status RNP\"\r\nFROM ping_metrics\r\nWHERE target = 'rnp.br'\r\n"
    }
   ]
  },
  {
   "title": "[ PING ] - TEMPO DE RESPOSTA (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  response_time_ms AS \"Latência Google\"\r\nFROM ping_metrics\r\nWHERE target = 'google.com'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  response_time_ms AS \"Latência UOL\"\r\nFROM ping_metrics\r\nWHERE target = 'uol.com.br'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  response_time_ms AS \"Latência RNP\"\r\nFROM ping_metrics\r\nWHERE target = 'rnp.br'\r\n"
    }
   ]
  },
  {
   "title": "[ HTTP ] - TEMPO DE CARREGAMENTO (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_load_time_ms AS \"Tempo de Carregamento Google\"\r\nFROM ping_metrics\r\nWHERE target = 'google.com'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_load_time_ms AS \"Tempo de Carregamento UOL\"\r\nFROM ping_metrics\r\nWHERE target = 'uol.com.br'\r\n"
    },
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_load_time_ms AS \"Tempo de Carregamento RNP\"\r\nFROM ping_metrics\r\nWHERE target = 'rnp.br'\r\n"
    }
   ]
  },
  {
   "title": "STATUS GOOGLE.COM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_status_code AS \"Status Google\"\r\nFROM ping_metrics\r\nWHERE target = 'google.com'"
    }
   ]
  },
  {
   "title": "STATUS RNP.BR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_status_code AS \"Status MP\"\r\nFROM ping_metrics\r\nWHERE target = 'rnp.br'"
    }
   ]
  },
  {
   "title": "STATUS UOL.COM.BR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  created_at AS \"time\", \r\n  http_status_code AS \"Status UOL\"\r\nFROM ping_metrics\r\nWhere target = 'uol.com.br'"
    }
   ]
  }
 ]
}