services:
  postgres:
    image: postgres:16
    container_name: ping-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: docker-db
      POSTGRES_USER: docker-user
      POSTGRES_PASSWORD: docker-pass
    ports:
      - "5432:5432"
    volumes:
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - rnp-network

networks:
  rnp-network:
    name: rnp-network
